---
title: "Morphology"
author: "Eric Coyle"
date: "6/2/2021"
output:
  word_document: 
    keep_md: yes
  html_document:
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(StereoMorph)
library(ggplot2)
library(here)
library(ggthemes)
library(paletteer)
library(ggpubr)
```

```{r}
morphology_data <- readr::read_csv("morphology_data.csv")
```
```{r}
head(morphology_data)
```

```{r}
morphology_data%>%
  ggplot(aes(x=proportion_body_ram,y=gape_cm,shape=species,size=`speed (m/s)`))+
  geom_point()
```
```{r}
morphology_data%>%
  ggplot(aes(x=proportion_body_ram,y=gape_cm,size=`speed (m/s)`))+
  geom_point()+
  geom_smooth(method = lm,se=F)+
  stat_regline_equation(label.y=1.9,aes(label = ..eq.label..)) +
  stat_regline_equation(label.y=1.8,aes(label = ..rr.label..))+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 60, hjust=1,size = 13),axis.title = element_text(size = 16),plot.title = element_text(size = 19,face = "bold",hjust = .5))+
  labs(title = "The influence of Body Ram on Gape",x="Proportion of Total Distance Covered by Body Ram",y="Gape (cm)")
```
```{r}
morphology_data%>%
  ggplot(aes(x=proportion_body_ram,y=gape_cm,size=`speed (m/s)`))+
  geom_point()+
  geom_smooth(method = lm,se=F)+
  stat_regline_equation(label.y=1.75,aes(label = ..eq.label..)) +
  stat_regline_equation(label.y=1.65,aes(label = ..rr.label..))+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 60, hjust=1,size = 13),axis.title = element_text(size = 16),plot.title = element_text(size = 19,face = "bold",hjust = .5))+
  labs(title = "The influence of Body Ram on Gape",x="Proportion of Total Distance Covered by Body Ram",y="Gape (cm)")+
  facet_wrap(~species)
```


```{r}
morphology_data%>%
  ggplot(aes(x=`speed (m/s)`,y=gape_cm))+
  geom_point()+
  geom_smooth(method = lm,se=F)+
  stat_regline_equation(label.y=1.9,aes(label = ..eq.label..)) +
  stat_regline_equation(label.y=1.8,aes(label = ..rr.label..))+
  theme(legend.position = "right",
        axis.text.x = element_text(angle = 60, hjust=1,size = 14),axis.title = element_text(size = 17),plot.title = element_text(size = 20,face = "bold",hjust = .5))+
  labs(title = "Gape of fish moving different speeds",x="Speed (m/s)",y="Gape (cm)")
```

