---
title: "LORR"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
library(tidyverse)
```


```{r}
LORR<-read.csv("LORR MC MP_Final.csv")
```

```{r}
LORR1<-LORR%>%
  mutate(Log_Length=log(Length))%>%
  mutate(Log_Weight=log(Weight))
```

```{r}
Body_index<-as.numeric(LORR$Body.Index)
LORR1<-LORR1%>%
  add_column(Body_index)
```


```{r}
LORR1_filtered<-LORR1%>%
  filter(Temp1!="NA")
```



```{r}
Linear<-lm(Log_Weight~Log_Length, data = LORR1)
print(Linear)
```

```{r}
summary(Linear)
```
```{r}
LORR1%>%
  ggplot(aes(x=Log_Length,y=Log_Weight))+
  geom_point()+
  geom_smooth(method = lm,formula = y ~ x,se=F)
```

```{r}
LORR1%>%
  ggplot(aes(x=Length,y=Temp_Ave,color=Date))+
  geom_point()+
  geom_smooth(se=F,method = lm)
```


```{r}
LORR1%>%
  ggplot(aes(x=Body_index,y=Temp_Ave))+
  geom_point()+
  geom_smooth(se=F,method = lm)
```
```{r}
LORR1_filtered%>%
  ggplot(aes(x=Weight,y=Temp_Ave,color=Date))+
  geom_point()+
  geom_smooth(se=F,method = lm)
```

```{r}
LORR1_filtered%>%
  ggplot(aes(x=Body_index,y=Temp_Ave,color=Date))+
  geom_point()+
  geom_smooth(se=F,method = lm)
```

```{r}
LORR1_filtered%>%
  group_by(Date)%>%
  summarise(mean_temp=mean(Temp_Ave))%>%
  ggplot(aes(x=Date,y=mean_temp,color=Date))+
  geom_point()
```
```{r}
one_way<-aov(Temp_Ave~Date, data = LORR1_filtered)
summary(one_way)
```
```{r}
one_way_bi<-aov(Body_index~Date, data = LORR1_filtered)
summary(one_way_bi)
```


```{r}
TukeyHSD(one_way)
```
```{r}
TukeyHSD(one_way_bi)
```


```{r}
LORR1_filtered%>%
  ggplot(aes(x=Date,y=Temp_Ave,color=Date))+
  geom_boxplot()
```
```{r}
LORR1_filtered%>%
  group_by(Date)%>%
  summarise(mean_BI=mean(Body_index))%>%
  ggplot(aes(x=Date,y=mean_BI,color=Date))+
  geom_point()
```
```{r}
LORR1_filtered%>%
  group_by(Date)%>%
  summarise(mean_BI=mean(Body_index),
            mean_LORR=mean(Temp_Ave))%>%
  ggplot(aes(x=mean_BI,y=mean_LORR,color=Date))+
  geom_point(size=3)
```
```{r}
LORR1_filtered%>%
  ggplot(aes(x=Date,y=Body_index,color=Date))+
  geom_boxplot()
```
```{r}
library(moderndive)
```

```{r}
BI_model<-lm(Temp_Ave~Body_index, data = LORR1_filtered)
```
##
```{r}
get_regression_table(BI_model)
```
```{r}
get_regression_summaries(BI_model)
```
```{r}
library(broom)
```


```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Body_index, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)
```
```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Body_index, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = r.squared, fill=Date)) +
    geom_bar(stat = "identity") +
    labs(x = "Date", y = expression(R^{2}))
```
```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Body_index, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for BI impact on LOEB Temp")
```
```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Weight, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for Weight impact on LOEB Temp")
```
```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Length, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for Length impact on LOEB Temp")
```
```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Length + Weight + Width, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for Measurments vs LOEB Temp")
```

```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Length + Weight, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for Measurments-2 vs LOEB Temp")
```
```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Width + Weight, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for Measurments-3 vs LOEB Temp")
```

```{r}
LORR1_filtered%>%
nest(-Date) %>% 
  mutate(fit = map(data, ~ lm(Temp_Ave ~ Width, data = .)),
         results = map(fit, glance)) %>% 
  unnest(results)%>%
ggplot(aes(x = factor(Date), y = round(p.value, digits = 4), fill=Date)) +
    geom_bar(stat = "identity") +
  geom_text(aes(label=round(p.value, digits = 4), vjust=1))+
    labs(x = "Date", y = "P value for Width vs LOEB Temp")
```
```{r}
LORR1_filtered%>%
  ggplot(aes(x=Width,y=Temp_Ave,color=Date))+
  geom_point()+
  geom_smooth(se=F,method = lm)
```

